#!/usr/bin/python3
import os
import xmlrpc.client
import json
import sys
import yaml

DATADIR = os.path.dirname(__file__)


def run(server_url, advisory_id):
    server = xmlrpc.client.ServerProxy(server_url)

    data = {
        "advisory_id": advisory_id,
        "cdn_metadata": server.get_advisory_cdn_metadata(advisory_id),
        "cdn_file_list": server.get_advisory_cdn_file_list(advisory_id),
        "cdn_docker_file_list": server.get_advisory_cdn_docker_file_list(advisory_id),
        "ftp_paths": server.get_ftp_paths(advisory_id),
    }

    data_file = os.path.join(DATADIR, "%s.yaml" % advisory_id)
    with open(data_file, "w") as fh:
        yaml.dump(data, fh)
    print("Wrote to", data_file)


if __name__ == "__main__":
    run(*sys.argv[1:])
