from typing import Text, TypeVar, Type, Sequence, Optional

PushItem_co = TypeVar("PushItem_co", bound="PushItem", covariant=True)
PushItem_contra = TypeVar("PushItem_contra", bound="PushItem", contravariant=True)

class KojiBuildInfo(object):
    name: Text
    version: Text
    release: Text
    @classmethod
    def _from_nvr(cls: Type["KojiBuildInfo"], nvr_str: Text) -> "KojiBuildInfo": ...

class PushItem(object):
    name: Text
    state: Text = ...
    src: Optional[Text] = ...
    dest: Sequence[Text] = ...
    md5sum: Optional[Text] = ...
    sha256sum: Optional[Text] = ...
    origin: Optional[Text] = ...
    build: Optional[Text] = ...
    build_info: KojiBuildInfo = ...
    signing_key: Optional[Text] = ...
    def with_checksums(self) -> "PushItem": ...
