from typing import Text, TypeVar, Type, Sequence, Optional

BuildInfo = TypeVar("BuildInfo", bound="KojiBuildInfo")

class KojiBuildInfo(object):
    name: Text
    version: Text
    release: Text
    @classmethod
    def _from_nvr(cls: Type[BuildInfo], nvr_str: Text) -> BuildInfo: ...

class PushItem(object):
    name: Text
    state: Text = ...
    src: Optional[Text] = ...
    dest: Sequence[Text] = ...
    md5sum: Optional[Text] = ...
    sha256sum: Optional[Text] = ...
    origin: Optional[Text] = ...
    build: Optional[Text] = ...
    build_info: BuildInfo = ...
    signing_key: Optional[Text] = ...
    def with_checksums(self) -> "PushItem": ...
